"""изменил схему чатов

Revision ID: 34e32a691568
Revises: bf143cb75081
Create Date: 2026-05-26 04:20:15.182296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e32a691568'
down_revision: Union[str, Sequence[str], None] = 'bf143cb75081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('bot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('bot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
