"""изменил схему чатов 2

Revision ID: 3d1ba656bbd2
Revises: 34e32a691568
Create Date: 2026-05-26 05:11:57.547471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1ba656bbd2'
down_revision: Union[str, Sequence[str], None] = '34e32a691568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_chats')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_chat_id'))
        batch_op.create_index(batch_op.f('ix_chats_chat_external_id'), ['chat_external_id'], unique=False)
        batch_op.create_foreign_key('fk_chats_member_id', 'users', ['member_id'], ['id'])
        batch_op.create_foreign_key('fk_chats_owner_id', 'users', ['owner_id'], ['id'])
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.BIGINT(), nullable=True))
        batch_op.drop_constraint('fk_chats_owner_id', type_='foreignkey')
        batch_op.drop_constraint('fk_chats_member_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chats_chat_external_id'))
        batch_op.create_index(batch_op.f('ix_chats_chat_id'), ['chat_id'], unique=False)

    op.create_table('_alembic_tmp_chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bot_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('chat_external_id', sa.BIGINT(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name=op.f('fk_chats_member_id')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_chats_owner_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
