"""добавил для сообщний юзернейм

Revision ID: fd339b11fd12
Revises: 3d1ba656bbd2
Create Date: 2026-05-26 06:21:36.842799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd339b11fd12'
down_revision: Union[str, Sequence[str], None] = '3d1ba656bbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_chats')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bot_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('chat_external_id', sa.BIGINT(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], name=op.f('fk_chats_member_id')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_chats_owner_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
